name: Java Build

on: [push]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v1
    - name: Set up OpenJDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'
        architecture: x64
    - name: Build with Gradle
      run: ./gradlew dist --info
    - name: Upload Installer
      uses: actions/upload-artifact@v1
      with:
        name: fx2048-1.0.pkg
        path: build/jpackage/fx2048-1.0.pkg
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v1
    - name: Set up OpenJDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'
        architecture: x64
    - name: Build with Gradle
      run: ./gradlew dist --info
    - name: Upload Installer
      uses: actions/upload-artifact@v1
      with:
        name: fx2048-1.0.msi
        path: build/jpackage/fx2048-1.0.msi
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v1
    - name: Set up OpenJDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'
        architecture: x64
    - name: Build with Gradle
      run: ./gradlew dist --info
    - name: List installers
      run: ls -l build/jpackage/
    - name: Upload Installer
      uses: actions/upload-artifact@v1
      with:
        name: fx2048-1.0.deb
        path: build/jpackage/fx2048_1.0-1_amd64.deb
