name: Java Build

on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

env:
  JAVA_VERSION: '25'
  JAVA_DISTRIBUTION: 'microsoft'
  JAVA_ARCHITECTURE: 'x64'

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v5
    - name: Set up OpenJDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v5
      with:
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        java-version: ${{ env.JAVA_VERSION }}
        architecture: ${{ env.JAVA_ARCHITECTURE }}
        cache: maven
    - name: Build with Maven
      run: ./mvnw --batch-mode --no-transfer-progress -DskipTests package javafx:jlink jpackage:jpackage
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: fx2048-macos
        path: target/dist/*.dmg

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v5
    - name: Set up OpenJDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v5
      with:
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        java-version: ${{ env.JAVA_VERSION }}
        architecture: ${{ env.JAVA_ARCHITECTURE }}
        cache: maven
    - name: Build with Maven
      run: ./mvnw --batch-mode --no-transfer-progress -DskipTests package javafx:jlink jpackage:jpackage
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: fx2048-windows
        path: target/dist/*.msi

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v5
    - name: Set up OpenJDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v5
      with:
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        java-version: ${{ env.JAVA_VERSION }}
        architecture: ${{ env.JAVA_ARCHITECTURE }}
        cache: maven
    - name: Build with Maven
      run: ./mvnw --batch-mode --no-transfer-progress -DskipTests package javafx:jlink jpackage:jpackage
    - name: List packages
      run: ls -l target/dist/
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: fx2048-linux
        path: target/dist/*.deb
